<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?php echo $title; ?></title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<link rel="stylesheet" href="<?= PATH ?>/public/css/estilo.css">
<script type="application/javascript" src="<?= PATH ?>/public/js/site.js"></script>
</head>

<body>
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand" href="<?=PATH?>/">
      <img alt="Brand" src="<?=PATH?>/public/img/logo.png">
        Animais
      </a>
    </div>
  </div>
</nav>



</header>
