<div class="container">
    <h2 class="center">Novo Animal</h2>
    <div class="row">
        <div class="col-md-8 col-md-offset-3 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="center"> Editar de Animal </p>

                </div>
                <div class="panel-body">
                    <form action="<?= PATH ?>/<?=$post->id?>/edit" method="post" enctype="multipart/form-data">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Nome</label>
                        <input type="text" class="form-control" id="exampleInputEmail1"  name="nome" aria-describedby="emailHelp" placeholder="Nome" value="<?=$post->nome ?>">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Raça</label>
                        <input type="text" class="form-control" id="exampleInputPassword1" name="raca" placeholder="Raça" value="<?=$post->raca ?>">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">peso</label>
                        <input type="number" step="any" class="form-control" id="exampleInputPassword1" name="peso" placeholder="peso"value="<?=$post->peso ?>">
                      </div>

                      <button type="submit" class="btn btn-primary">Atualizar</button>
                    </form>


                </div>

<?php if(isset($error)): ?>
<div class="alert alert-warning" role="alert">
'               <?= $error ?>

                </div>
<?php endif; ?>

</div>

</div>
</div>
</div>